# parameters:
# - name: gitUsername
#   type: string
# - name: repoName
#   type: string
# - name: branchName
#   type: string
# - name: PROJECTKEY
#   type: string
# - name: SONAR_URL
#   type: string
# - name: SONAR_TOKEN
#   type: string

trigger:
- main

pool: Default

steps:
  - script: echo "Git Clone"
    displayName: 'Git Clone'
    env:
      GIT_USERNAME: $(gitUsername)
      REPO_NAME: $(repoName)
      BRANCH_NAME: $(branchName)
    continueOnError: false

  - script: |
      echo Starting the build
      mvn package
    displayName: 'Build with Maven'

  - script: |
      echo "Running SonarQube Scan"
      sonar-scanner.bat -X -D"sonar.projectKey=$(PROJECTKEY)" -D"sonar.sources=." -D"sonar.host.url=$(SONAR_URL)" -D"sonar.token=$(SONAR_TOKEN)" -D"sonar.sources=src/main/java/" -D"sonar.java.binaries=src/main/java/com/dockerforjavadevelopers/hello/"
    displayName: 'Run SonarQube Scanning'

  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/target/*.?(war|jar)'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: SpringBootArtifact