parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: jenkins
- name: branchName
  type: string
  default: main
- name: dockerImageName
  type: string
  default: myapp
- name: sonarqubeProjectKey
  type: string
  default: aishwaryaaraghuraman_azuredevops

- name: sonarqubeToken
  type: string
 
trigger:
- main

variables:
  SONAR_TOKEN: 7086d78878ddbb7c0df099499599229f5a022093


pool: Default
 
steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false
 
 
- script: |
    sonar-scanner.bat \
    -D"sonar.organization=aishwaryaaraghuraman" \
    -D"sonar.projectKey=aishwaryaaraghuraman_azuredevops" \
    -D"sonar.sources=." \
    -D"sonar.host.url=https://sonarcloud.io"
  displayName: 'Run SonarQube Scan'
 
- script: |
    echo "Cleaning Local Directory"
    sudo rm -rf *
  displayName: 'Clean Local Directory'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'build-artifact'
    publishLocation: 'pipeline'