# Azure DevOps YAML pipeline script for Springboot application using Maven
trigger:
  branches:
    include:
      - master
variables:
  buildConfiguration: 'Release'

# Stages
  stages:
   - Build
# Jobs
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            publishJUnitResults: false

