parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: jenkins
- name: branchName
  type: string
  default: main


trigger:
- main
 
pool: Default
 
steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '38bb69e9-e228-424f-8b11-902e3f2bea0e'
    pipeline: '11'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    tags: 'azure1'
    downloadType: 'single'
    artifactName: 'build-artifact'
    downloadPath: '$(System.ArtifactsDirectory)'



