trigger:

- main
 
pool: Default
 
steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '38bb69e9-e228-424f-8b11-902e3f2bea0e'
    pipeline: '11'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/main'
    tags: 'lastest'
    downloadType: 'single'
    artifactName: 'build-artifact'
    downloadPath: '$(Pipeline.Workspace)'