# Azure Pipelines YAML file for Springboot application

# Parameters
parameters:
- name: gitUsername
  type: string
  default: 'ruchi672'
- name: repoName
  type: string
  default: 'homepage-app-springboot-jar'
- name: branchName
  type: string
  default: 'master'

# Stages
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
    - task: SonarQubePreBuild@1
      inputs:
          projectKey: '21'
          projectName: 'sonar'
          projectVersion: '1.0'
          dbUrl: 'Sonar'
          dbUsername: 'sonar_db'
          dbPassword: 'sonar'   
    - task: PublishBuildArtifacts@1
      inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'