# Azure DevOps YAML pipeline script for Springboot application using Maven

# Parameters
parameters:
  vmImage: 'ubuntu-latest'
  repository: 'my-spring-boot-app'
  dockerfile: 'Dockerfile'
  containerRegistry: 'my-container-registry'

# Variables
variables:
  buildConfiguration: 'Release'

# Stages
stages:
  - Build
  - PushImage

# Jobs
jobs:
  - job: Build
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          publishJUnitResults: false

  - job: PushImage
    dependsOn: Build
    pool:
      vmImage: $(vmImage)
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: $(dockerfile)