parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: jenkins
- name: branchName
  type: string
  default: main


trigger:
- main
 
pool: Default
# Stages
stages:
- stage: CloneRepo
  displayName: Clone Git Repository
  jobs:
  - job: CloneRepoJob
    displayName: Clone Git Repository
    steps:
     - script: echo "Git Clone"
       displayName: 'Git Clone'
       env:
         GIT_USERNAME: $(gitUsername)
         REPO_NAME: $(repoName)
         BRANCH_NAME: $(branchName)
       continueOnError: false
      

- stage: DeployToKubernetes
  displayName: Deploy to Kubernetes
  dependsOn: CloneRepo
  jobs:
  - job: DeployToKubernetesJob
    displayName: Deploy to Kubernetes
    steps:
    - task: KubernetesManifest@0
      displayName: Apply Kubernetes Manifest
      inputs:
        kubernetesServiceConnection: 'Azure Kubernetes Service'
        namespace: 'default'
        manifests: 'deploy.yml'
        action: 'apply'

