parameters:
- name: gitUsername
  type: string
  default: ruchi672
- name: repoName
  type: string
  default: homepage-app-springboot-jar
- name: branchName
  type: string
  default: master


trigger:
- main
 
pool: Default
 
steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false
 
 
- script: |
    echo "Running SonarQube Scan"
    sonar-scanner.bat -D"sonar.projectKey=AzureDevops" -D"sonar.sources=." -D"sonar.host.url=http://10.198.32.133:9000" -D"sonar.token=sqp_fb337fa6155bad0e72f5834351858930234bba03" -D"sonar.sources=src/main/java/" -D"sonar.java.binaries=src/main/java/com/charan/homepageappspringbootjar/"
  displayName: 'Run SonarQube Scan'
 
- script: |
    echo "Quality gate"
    mvn sonar:sonar -Dsonar.qualitygate.wait=true
  displayName: "Quality Gate"

- script: |
    echo "Cleaning Local Directory"
    rm -rf *
  displayName: 'Clean Local Directory'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'build-artifact'
    publishLocation: 'pipeline'