# Azure Pipelines YAML file for a Springboot application with Maven build and SonarQube analysis

# Parameters
parameters:
- name: framework
  type: string
  default: springboot
- name: buildTool
  type: string
  default: maven
- name: gitUsername
  type: string
- name: repoName
  type: string
- name: branchName
  type: string

# Stages
stages:
- clone
- build
- test
- deploy

# Jobs
jobs:
  - job: CloneRepo
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: true
        submodules: true
        fetchDepth: 1
      - script: |
          sudo apt-get update
          sudo apt-get install git
          git clone https://github.com/${gitUsername}/${repoName}.git
          cd ${repoName}
          git checkout ${branchName}
    displayName: Clone Repository

  - job: Build
    dependsOn: CloneRepo
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          cd ${repoName}
          mvn clean install
    displayName: Build Application

  - job: Test
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          cd ${repoName}
          mvn sonar:sonar
    displayName: Run SonarQube Analysis

  - job: Deploy
    dependsOn: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          cd ${repoName}
          mvn clean package
          sudo cp target/*.jar /opt/nexus/nexus-data/storage/
    displayName: Deploy Application to Nexus

# Post-processing
postProcessing:
  clean: true