# Azure Pipelines YAML file for Springboot application

# Parameters
parameters:
- name: gitUsername
  type: string
  default: 'azureuser'
- name: repoName
  type: string
  default: 'spring-boot-app'
- name: branchName
  type: string
  default: 'main'

# Stages
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Checkout@2
      inputs:
        repositoryName: $(repoName)
        branch: $(branchName)
        clean: true
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'MSBuild'
        projectKey: '$(repoName)'
        projectName: '$(repoName)'
        projectVersion: '1.0'
    - task: SonarQubeAnalyze@4
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'MSBuild'
        buildProcessId: '$(Build.BuildId)'
    - task: SonarQubePublish@4
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'MSBuild'
    - task: SonarQubeQualityGate@4
      inputs:
        SonarQube: 'SonarQube'
        qualityGateName: 'SonarQubeQualityGate'
    - task: CleanDirectory@1
      inputs:
        path: '$(Agent.TempDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'