parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: jenkins
- name: branchName
  type: string
  default: main
- name: dockerImageName
  type: string
  default: myapp
- name: sonarqubeProjectKey
  type: string
  default: AzureDevops
- name: sonarqubeUrl
  type: string
  default: http://10.198.32.133:9000
- name: sonarqubeToken
  type: string
  default: sqp_fb337fa6155bad0e72f5834351858930234bba03
 
trigger:
- main
 
pool: Default
 
steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false

- script: |
    echo Starting the build
    mvn clean package
  displayName: 'Build with Maven'

 
- script: |
    echo "Running SonarQube Scan"
    docker run -e SONAR_HOST_URL=$(sonarqubeUrl) \
                  -e SONAR_LOGIN=$(sonarqubeToken) \
                  -e SONAR_PROJECT_KEY=$(sonarqubeProjectKey) \
                  $(dockerImageName)
  displayName: 'Run SonarQube Scan'
 
- task: Docker@2
  inputs:
     repository: 'Azure'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
  displayName: 'Build Docker Image'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'build-artifact'
    publishLocation: 'pipeline'