parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: jenkins
- name: branchName
  type: string
  default: main


trigger:
- main

jobs:
- job: Build 
  displayName: 'Build JAVA Application'
  pool: Default
 
  steps:
  - script: echo "Git Clone"
    displayName: 'Git Clone'
    env:
      GIT_USERNAME: $(gitUsername)
      REPO_NAME: $(repoName)
      BRANCH_NAME: $(branchName)
    continueOnError: false
  
  - script: |
      echo Starting the build
      mvn package
    displayName: 'Build with Maven'
      
  - script: |
      echo "Running SonarQube Scan"
      sonar-scanner.bat -D"sonar.projectKey=$(projectkey)" -D"sonar.sources=." -D"sonar.host.url=$(SONAR_URL)" -D"sonar.token=$(SONAR_TOKEN)" -D"sonar.sources=src/main/java/" -D"sonar.java.binaries=src/main/java/com/dockerforjavadevelopers/hello/"
    displayName: 'Run SonarQube Scanning'

  # - task: PublishPipelineArtifact@1
  #   inputs:
  #     targetPath: '$(Pipeline.Workspace)'
  #     artifact: 'build-artifact'
  #     publishLocation: 'pipeline'

  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: SampleSpringBootBuild

- job: Deploy
  displayName: 'Deploy JAVA Application'
  pool: Default
  steps:
  # - task: DownloadBuildArtifacts@1
  #   inputs:
  #     buildType: 'specific'
  #     project: '38bb69e9-e228-424f-8b11-902e3f2bea0e'
  #     pipeline: '11'
  #     buildVersionToDownload: 'latestFromBranch'
  #     branchName: 'refs/heads/main'
  #     tags: 'lastest'
  #     downloadType: 'single'
  #     artifactName: 'build-artifact'
  #     downloadPath: '$(Pipeline.Workspace)'
  
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '38bb69e9-e228-424f-8b11-902e3f2bea0e'
      definition: 'AishwaryaaRaghuraman.jenkins'
      buildVersionToDownload: 'latest'
      # targetPath: '$(Pipeline.Workspace)'
      downloadPath: '$(Build.ArtifactStagingDirectory)'
  
  - script: 
      # cd $(System.DefaultWorkingDirectory)
      cd /azure/2/a/SampleSpringBootBuild/target
      java -jar hello-world-0.1.0.jar
    displayName: "Deploy JAVA Application"