# Azure Pipelines YAML file for a DevOps Engineer build pipeline

# Parameters
parameters:
  - name: gitUsername
    displayName: Git Username
    type: string
    default: 'my-git-username'
  - name: repoName
    displayName: Repository Name
    type: string
    default: 'my-repo-name'
  - name: branchName
    displayName: Branch Name
    type: string
    default: 'main'
  - name: framework
    displayName: Framework
    type: string
    default: 'Springboot'
  - name: buildTool
    displayName: Build Tool
    type: string
    default: 'Maven'

# Stages
stages:
  - stage: Clone
    displayName: Clone Repository
    jobs:
      - job: CloneRepo
        displayName: Clone Repository
        steps:
          - checkout: self
            clean: true
            submodules: true

  - stage: Build
    displayName: Build Project
    jobs:
      - job: BuildProject
        displayName: Build Project
        steps:
          - script: mvn clean package
            displayName: Build Project

  - stage: SonarScan
    displayName: Perform SonarScan
    jobs:
      - job: SonarScan
        displayName: Perform SonarScan
        steps:
          - script: sonar-scanner -Dsonar.projectKey=${REPO_NAME} -Dsonar.sources=src/main/java -Dsonar.java.binaries=target/classes
            displayName: SonarScan 

  - stage: QualityGate
    displayName: Check Quality Gate
    jobs:
      - job: QualityGate
        displayName: Check Quality Gate
        steps:
          - script: sonar-quality-gate -Dsonar.projectKey=${REPO_NAME}
            displayName: QualityGate

  - stage: Clean
    displayName: Clean Local Directory
    jobs:
      - job: CleanLocalDirectory
        displayName: Clean Local Directory
        steps:
          - script: sudo rm -rf *
            displayName: Clean Local Directory

              