parameters:
- name: gitUsername
  type: string
  default: ruchi672
- name: repoName
  type: string
  default: homepage-app-springboot-jar
- name: branchName
  type: string
  default: master


trigger:
- main
 
pool: Default
 
steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false
 
 
- script: |
    echo "Running SonarQube Scan"
    mvn sonar:sonar
  displayName: 'Run SonarQube Scan'
 
- script: |
    echo "Cleaning Local Directory"
    sudo rm -rf *
  displayName: 'Clean Local Directory'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'build-artifact'
    publishLocation: 'pipeline'